
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: check-added-large-files
      language_version: python3
    - id: check-ast
      language_version: python3
    - id: check-case-conflict
      language_version: python3
    - id: check-docstring-first
      language_version: python3
    - id: check-json
      language_version: python3
    - id: check-merge-conflict
      language_version: python3
    - id: check-xml
      language_version: python3
    - id: check-yaml
      language_version: python3
    - id: debug-statements
      language_version: python3
    - id: detect-private-key
      language_version: python3
    - id: end-of-file-fixer
      language_version: python3
    - id: requirements-txt-fixer
      language_version: python3
    - id: trailing-whitespace
      language_version: python3
- repo: git://github.com/asottile/reorder_python_imports
  rev: v1.0.1
  hooks:
    - id: reorder-python-imports
      language_version: python3
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4
  hooks:
  - id: autopep8
    language_version: python3
    args: ['-i', '--max-line-length=120']
