version: 2
jobs:
  build:
    working_directory: ~/python-learning-cli-project
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install -r requirements.txt
            sudo pip install pylint
            cd ..
            pylint python-learning-cli-project --ignore=venv --rcfile=python-learning-cli-project/.pylintrc
